"""Build HTML documentation from reStructured Text files generated by Sphinx.
If documentation is to be hosted elsehwere (e.g. `Read the Docs <https://readthedocs.org/>`_)
then there is no need to use this module.

NOTE: 
    Intended to be run locally.
"""

from autodoc.build.build_docs import build_docs as build


def build_docs(outdir: str) -> None:
    """Builds Sphinx HTML documentation locally.

    The output location of the documentation should be: ``<outdir>/doc/build``.

    Args:
        outdir: Output parent directory.
    """
    build(outdir=outdir)
    return None
